services:
  tms-automation:
    build: .
    image: tms-automation:all-in-one
    container_name: tms-automation
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      DB_USER: pk
      DB_PASSWORD: pk
      DB_HOST: 127.0.0.1
      DB_NAME: stock
      FRONTEND_SEED_USER: admin
      FRONTEND_SEED_PASSWORD: admin
    volumes:
      - tms_postgres_data:/var/lib/postgresql/data

volumes:
  tms_postgres_data:
