services:
  postgres:
    image: postgres:16-alpine
    container_name: tms-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pk
      POSTGRES_PASSWORD: pk
      POSTGRES_DB: stock
    volumes:
      - tms_postgres_data:/var/lib/postgresql/data

volumes:
  tms_postgres_data:
